### ISSUE TITLE
setup guide

### ISSUE THREAD

**Issue by Goldenstarc** [MaJerle/ESP_AT_Lib_res#1]
Hi,
may you put a little guide for first time run ?
where to put files and just a simple example.
does it need to change the Makefile ?
(I tried a lot !)

**Comment by MaJerle** [comment]
As explained in readme file.

1. Clone repository
2. Run git command and run examples (check first page for command).

**Comment by MaJerle** [comment]
Sorry, it is what? Please read how-to-start docs.

**Comment by MaJerle** [comment]
1. Library doesnt care about stm32, windows or mac.
2. Windows.h is used inly in files which are windows dependant. Dont use these files.

I wrote extended tutorial about what user has to do to port library to specific architecture.

As you can see Im using Windows for development (win32 port) but examples are running on STM32 too (there is no windows and it works).

**Comment by MaJerle** [comment]
Here detailed guide to download and run examples. Examples work on STM32 for TrueSTUDIO which works on MAC.

https://majerle.eu/documentation/esp_at/html/page_appnote.html#sect_clone_get_started
