### ISSUE TITLE
Is there a BUG in the RingBuffer Read char?

### ISSUE THREAD

**Issue by zhangxichao** [MaJerle/ESP_AT_Lib_res#2]
Hi Majerle!

In file esp_int.c

/**
 * \brief           Process data from input buffer
 * \return          \ref espOK on success, member of \ref espr_t enumeration otherwise
 */
espr_t
espi_process_buffer(void) {
    void* data;
    size_t len;

    do {
        /*
         * Get length of linear memory in buffer
         * we can process directly as memory
         */
        len = esp_buff_get_linear_block_length(&esp.buff);
        if (len) {
            /*
             * Get memory address of first element
             * in linear block to process
             */
            data = esp_buff_get_linear_block_address(&esp.buff);

            /*
             * Process actual received data
             */
            espi_process(data, len);

            /*
             * Once they are processed, simply skip
             * the buffer memory and start over
             */
            esp_buff_skip(&esp.buff, len);
        }
    } while (len);
    return espOK;
}

For example, if len = 3; the ring buffer's reading pointer（out） is at the end of the ring buffer,
Is there a problem that * d++ in function espi_process does not automatically go back to ringbuffer's head?

espr_t
espi_process(const void* data, size_t data_len) {
    uint8_t ch;
    size_t d_len = data_len;
    const uint8_t* d;
    static uint8_t ch_prev1, ch_prev2;
    static esp_unicode_t unicode;

    d = data;                                   /* Go to byte format */
    d_len = data_len;
    while (d_len) {                             /* Read entire set of characters from buffer */
        ch = *d++;                              /* Get next character */
        d_len--;                                /* Decrease remaining length */

        /*
         * First check if we are in IPD mode and process plain data
         * without checking for valid ASCII or unicode format
         */
        if (esp.ipd.read) {                     /* Do we have to read incoming IPD data? */
        ........
}

**Comment by zhangxichao** [comment]
Sorry，my english is terrible.

the function "espi_process_buffer" in file esp_int.c

len = esp_buff_get_linear_block_length(&esp.buff);
data = esp_buff_get_linear_block_address(&esp.buff);

For example, if len = 3; the ring buffer's reading pointer（out） is at the end of the ring buffer,
Is there a problem that * d++ in function espi_process does not automatically go back to ringbuffer's head?

espi_process
{
    *d++; /*Is there a problem?*/
}

**Comment by MaJerle** [comment]
No, it is not a problem. If len = 3, then function `esp_buff_get_linear_block_address` returns beginning of these `3` bytes. After, there is a call to `esp_buff_skip` which will skip these bytes and will check for overwriting.

No bug here.

**Comment by zhangxichao** [comment]
esp_buff_skip is called after *d++?

**Comment by MaJerle** [comment]
Please refer to function `espi_process_buffer` what it does. By C language, this is all valid, unless I do not understand your point :)

**Comment by zhangxichao** [comment]
the function "espi_process_buffer" in file esp_int.c，

len = esp_buff_get_linear_block_length(&esp.buff);

For example, if len = 3; 
and if the ring buffer's reading pointer（out） is at the end of the ring buffer,

Now，these 3 bytes is The last one，The first and The second element of the ringbuffer.

data = esp_buff_get_linear_block_address(&esp.buff);

The “data” pointer now points to the last address.

Then call the “espi_process ”function，
espi_process
{
    while (len) {                             /* len = 3 */
    ch = *d++;                              /* d++ does not automatically go back to the first one*/
    ......
    }
    
}

Finally, the "esp_buff_skip " function is called.But the previous three Bytes have gone wrong.

Is this a BUG?

**Comment by MaJerle** [comment]
@zhangxichao no. Please check what `esp_buff_get_linear_block_length` actually returns. It is always valid.

**Comment by zhangxichao** [comment]
Thanks,MaJerle!
I See.
