### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by zhangxichao** [MaJerle/ESP_AT_Lib_res#3]
Hi Majerle,

in esp_at_lib_res\dev\src\main.c：

void
EXTI3_IRQHandler(void) {
    if (is_device_present()) {
        printf("Device present!\r\n");
        esp_device_set_present(1, 0);           /* Notify stack about device present */
        esp_reset_with_delay(2000, NULL, NULL, 0);
    } else {
        printf("Device disconnected!\r\n");
        esp_device_set_present(0, 0);           /* Notify stack about device not connected anymore */
    }
    EXTI->PR = GPIO_PIN_3;
}

The function “esp_device_set_present” actually has four parameters, but only two parameters are passed here, resulting in project compilation errors.

**Comment by MaJerle** [comment]
Dev is development folder and contains lots of dummy code.

**Comment by zhangxichao** [comment]
Hi Majerle,
I found a problem in funtion esp_thread_producer of the file esp_threads.c
in Line 95, 
If the semaphore(sem_sync) timed out, I didn't see you releasing it.
Is there something wrong with my understanding?

**Comment by MaJerle** [comment]
That's how semaphores work. You have to release it only if you acquire it. If wait function timeouts, then there is nothing to release.

**Comment by zhangxichao** [comment]
If a timeout occurs, the semaphore lock is not acquired and naturally no release is required.
thanks MaJerle!
